const PgModel = require('./pgModel');

module.exports = new PgModel({
  table: 'consignments',
  fields: [
    '_id',
    'id',
    'lrNumber',
    'bookingDate',
    'bookingTime',
    'consignerId',
    'consigneeId',
    'tripId',
    'invoiceNumber',
    'invoiceDate',
    'ewayBillNumber',
    'ewayBillDate',
    'ewayBillValidUpto',
    'description',
    'packageType',
    'packageCount',
    'dimensions',
    'rate',
    'bookingMode',
    'modeOfDelivery',
    'paymentMode',
    'deliveryDate',
    'partNumber',
    'partName',
    'quantity',
    'privateMark',
    'actualWeight',
    'chargeableWeight',
    'goodsValue',
    'freight',
    'collectionCharges',
    'doorDeliveryCharges',
    'hamali',
    'stCharges',
    'otherCharges',
    'insurance',
    'subTotal',
    'gst',
    'sgst',
    'cgst',
    'igst',
    'totalAmount',
    'remarks',
    'status',
    'billStatus',
    'paymentStatus',
    'freightBillId',
    'createdAt',
    'updatedAt',
  ],
});
