const mongoose = require('mongoose');

const consignmentSchema = new mongoose.Schema({
  lrNumber: { type: String, required: true, unique: true },
  bookingDate: { type: Date, required: true },
  bookingTime: { type: String, required: true },
  consignerId: { type: mongoose.Schema.Types.ObjectId, required: true, ref: 'Customer' },
  consigneeId: { type: mongoose.Schema.Types.ObjectId, required: true, ref: 'Customer' },
  tripId: { type: mongoose.Schema.Types.ObjectId, required: true, ref: 'Trip' },
  invoiceNumber: { type: String },
  invoiceDate: { type: Date },
  ewayBillNumber: { type: String },
  ewayBillDate: { type: Date },
  ewayBillValidUpto: { type: Date },
  description: { type: String },
  packageType: { type: String },
  packageCount: { type: Number, default: 0 },
  dimensions: { type: String },
  rate: { type: Number, default: 0 },
  bookingMode: { type: String },
  modeOfDelivery: { type: String },
  paymentMode: { type: String },
  deliveryDate: { type: Date },
  partNumber: { type: String },
  partName: { type: String },
  quantity: { type: Number, default: 0 },
  privateMark: { type: String },
  actualWeight: { type: Number, default: 0 },
  chargeableWeight: { type: Number, default: 0 },
  goodsValue: { type: Number, default: 0 },
  freight: { type: Number, default: 0 },
  collectionCharges: { type: Number, default: 0 },
  doorDeliveryCharges: { type: Number, default: 0 },
  hamali: { type: Number, default: 0 },
  stCharges: { type: Number, default: 0 },
  otherCharges: { type: Number, default: 0 },
  insurance: { type: Number, default: 0 },
  subTotal: { type: Number, default: 0 },
  gst: { type: Number, default: 0 },
  sgst: { type: Number, default: 0 },
  cgst: { type: Number, default: 0 },
  igst: { type: Number, default: 0 },
  totalAmount: { type: Number, default: 0 },
  remarks: { type: String },
  status: { type: String, enum: ['Pending', 'In Transit', 'Delivered'], default: 'Pending' },
  billStatus: { type: String, enum: ['Not Billed', 'Not Generated', 'Bill Generated'], default: 'Not Billed' },
  paymentStatus: { type: String, enum: ['-', 'Pending', 'Paid'], default: '-' },
  freightBillId: { type: mongoose.Schema.Types.ObjectId, ref: 'FreightBill' },
}, {
  timestamps: true,
});

module.exports = mongoose.model('Consignment', consignmentSchema);
